let nombres_familiares = new Set(["Lucelly", "Jeffry", "Lizeth", "Jonathan"])
nombres_familiares.add("Jeffry")
console.log(nombres_familiares)
nombres_familiares.add("Javascript")
console.log(nombres_familiares)
